# Header
menu:
  Home: /
  Archives: /archives

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud
- archive
thumbnail: false

# Contacts
contacts:
  github: http://github.com/sazzer
  twitter: 'https://twitter.com/grahamcox82'
  rss: /atom.xml

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics: UA-62627767-1
favicon: /favicon.png
twitter: 'https://twitter.com/grahamcox82'
google_plus:
fb_admins:
fb_app_id:

root: /
